[package]
name = "bevy_autodiff"
version = "0.1.0"
edition = "2021"
description = "Automatic differentiation using Bevy ECS as computation graph"
license = "MIT"
repository = "https://github.com/VisVivaSpace/bevy_autodiff.git"

[dependencies]
bevy_ecs = "0.15"
bevy_entity_ptr = "0.1.0"
thiserror = "1.0"
bevy_autodiff-macros = { version = "0.1.0", path = "./bevy_autodiff-macros", optional = true }

[features]
default = []
std_autodiff_tests = []
proc-macros = ["bevy_autodiff-macros"]

[dev-dependencies]
approx = "0.5"
autodiff = "0.7"
criterion = "0.5"

[[bench]]
name = "compiled_vs_ecs"
harness = false

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "gradient"
path = "examples/gradient.rs"

[[example]]
name = "hessian"
path = "examples/hessian.rs"

[[example]]
name = "rosenbrock"
path = "examples/rosenbrock.rs"

[[example]]
name = "orbital_mechanics"
path = "examples/orbital_mechanics.rs"
